run:
  timeout: 5m
  tests: true

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - goimports
    - golint
    - misspell

linters-settings:
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.8

issues:
  exclude:
    - "exported function .* should have comment"
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
